version: "3.7"
services:
  db:
    image: mysql:8.0
    platform: linux/x86_64 # <-- Add this line for M1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: t2h_liquibase
      MYSQL_USER: t2h_liquibase
      MYSQL_PASSWORD: t2h_liquibase
    command: mysqld --default-authentication-plugin=mysql_native_password --sort_buffer_size=1073741824 --character_set_server=utf8mb4
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - default
      - shared-network

networks:
  shared-network:
    external: true
