create table kbboard (id bigint not null auto_increment, created_at datetime, deleted_at datetime, sorting_order bigint, edited_at datetime, updated_at datetime, version bigint, board_type varchar(255), title varchar(255) not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;
create table kbcard (id bigint not null auto_increment, created_at datetime, deleted_at datetime, sorting_order bigint, edited_at datetime, updated_at datetime, version bigint, assignees json, brand_uid varchar(255), contact_address varchar(255), contact_email varchar(255), contact_name varchar(255), contact_number varchar(255), detail varchar(255), due_date datetime, image_urls json, is_done bit, item_hash_id varchar(255), margin_price tinyblob, model_uid varchar(255), owner_hash_id varchar(10), price tinyblob, reporters json, title varchar(255), uid varchar(255), lane_id bigint, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;
create table kbcomment (id bigint not null auto_increment, created_at datetime, deleted_at datetime, sorting_order bigint, edited_at datetime, updated_at datetime, version bigint, bb_code varchar(255), owner_hash_id varchar(10), card_id bigint, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;
create table kblane (id bigint not null auto_increment, created_at datetime, deleted_at datetime, sorting_order bigint, edited_at datetime, updated_at datetime, version bigint, emit_events json, is_done_lane bit, is_init_lane bit, slug varchar(255) not null, title varchar(255), board_id bigint, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;
create table ktbrand (id bigint not null auto_increment, created_at datetime, deleted_at datetime, sorting_order bigint, edited_at datetime, updated_at datetime, version bigint, canonical_url_meta varchar(512), description TEXT, description_meta TEXT, image_url varchar(512), image_url_meta varchar(512), name varchar(255) not null, number_of_items bigint, placeholder varchar(255), search_synonym varchar(1024), slug varchar(255) not null, thai_name varchar(255), title_meta TEXT, uid bigint not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;
create table ktbrand_root_categories (brands_id bigint not null, root_categories_id bigint not null) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;
create table ktcategory (id bigint not null auto_increment, created_at datetime, deleted_at datetime, sorting_order bigint, edited_at datetime, updated_at datetime, version bigint, breadcrumb_path json, canonical_url_meta varchar(512), description TEXT, description_meta TEXT, image_url varchar(512), image_url_meta varchar(512), name varchar(255) not null, number_of_items bigint, path json, placeholder varchar(255), search_synonym varchar(512), slug varchar(255) not null, thai_name varchar(255), title_meta TEXT, uid bigint not null, master_index_id bigint, root_category_id bigint, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;
create table ktfile (id bigint not null auto_increment, created_at datetime, deleted_at datetime, sorting_order bigint, edited_at datetime, updated_at datetime, version bigint, category varchar(255), driver varchar(255), file_extension varchar(2048), file_original_name varchar(2048), file_type varchar(255), full_url varchar(2048), is_public bit, is_resized bit, path varchar(2048), real_path varchar(2048), size bigint, uid bigint, user_uid bigint, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;
create table ktmaster_index (dtype integer not null, id bigint not null auto_increment, created_at datetime, deleted_at datetime, sorting_order bigint, edited_at datetime, updated_at datetime, version bigint, attribute_data_type varchar(255), description TEXT, image_url varchar(512), name varchar(255) not null, placeholder varchar(255), slug varchar(255) not null, thai_name varchar(255) not null, uid bigint not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;
create table ktmenu (id bigint not null auto_increment, created_at datetime, deleted_at datetime, sorting_order bigint, edited_at datetime, updated_at datetime, version bigint, description TEXT, name varchar(255) not null, path json, uid bigint not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;
create table ktmodel (id bigint not null auto_increment, created_at datetime, deleted_at datetime, sorting_order bigint, edited_at datetime, updated_at datetime, version bigint, canonical_url_meta varchar(512), description TEXT, description_meta TEXT, image_url varchar(512), image_url_meta varchar(512), model_name varchar(255) not null, name varchar(255) not null, number_of_items bigint, placeholder varchar(255), search_synonym varchar(1024), slug varchar(255) not null, thai_name varchar(255), title_meta TEXT, uid bigint not null, brand_id bigint, root_category_id bigint, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;
alter table kbboard add constraint UK_f5ccqepfu0033cpq9rd36f3w0 unique (board_type);
alter table kbboard add constraint UK_9qwq08ccwfe7sbbtkjuu06cgk unique (title);
create index IDX_KBCARD_OWNERHASH_ID on kbcard (owner_hash_id);
alter table kbcard add constraint IDX_KBCARD_UID unique (uid);
create index IDX_KBCOMMENT_OWNERHASH_ID on kbcomment (owner_hash_id);
alter table kblane add constraint UK_978rbe3jfpye0o5bev6cwa7yw unique (slug);
create index IDX_KTBRAND_NAME on ktbrand (name);
create index IDX_KTBRAND_THAINAME on ktbrand (thai_name);
alter table ktbrand add constraint UK_m8g6cyhewn1j67u1glkkr4glc unique (slug);
alter table ktbrand add constraint UK_2fmf1e3b3t12rncsl1ydpqiwm unique (uid);
create index IDX_KTCATEGORY_NAME on ktcategory (name);
create index IDX_KTCATEGORY_THAINAME on ktcategory (thai_name);
create index IDX_KTCATEGORY_MASTERINDEX on ktcategory (master_index_id);
create index IDX_KTCATEGORY_ROOTCATEGORY on ktcategory (root_category_id);
alter table ktcategory add constraint UK_dls0exj68ut5d2jchvynltt60 unique (slug);
alter table ktcategory add constraint UK_hcf3oaqx2ogfdwdov65jdg39b unique (uid);
create index IDX_KTFILE_UID on ktfile (uid);
create index IDX_KTFILE_USERID on ktfile (user_uid);
create index IDX_KTMASTERINDEX_NAME on ktmaster_index (name);
create index IDX_KTMASTERINDEX_THAINAME on ktmaster_index (thai_name);
create index IDX_KTMASTERINDEX_DTYPE on ktmaster_index (dtype);
create index IDX_KTMASTERINDEX_ATTBTYPE on ktmaster_index (attribute_data_type);
alter table ktmaster_index add constraint UK_bjxubcw5qod15a4ohj1cy0lgs unique (slug);
alter table ktmaster_index add constraint UK_n4fbd7s9lhs9vk6j3wh0bhr4x unique (uid);
alter table ktmenu add constraint UK_crhs9rd7byegpm8y1dppppgwb unique (name);
alter table ktmenu add constraint UK_kv2657fkcuibl9aii1kvaroet unique (uid);
create index IDX_KTMODEL_NAME on ktmodel (name);
create index IDX_KTMODEL_MODELNAME on ktmodel (model_name);
create index IDX_KTMODEL_THAINAME on ktmodel (thai_name);
create index IDX_KTMODEL_BRAND on ktmodel (brand_id);
create index IDX_KTMODEL_ROOTCATEGORY on ktmodel (root_category_id);
alter table ktmodel add constraint UK_efrnoidlds6n2gsm9m4upuktw unique (slug);
alter table ktmodel add constraint UK_b3emqjen11ue6hs8jq5qbnnpu unique (uid);
alter table kbcard add constraint FKd6vbdjrq54xuk4mf9c992pmbi foreign key (lane_id) references kblane (id);
alter table kbcomment add constraint FKkvlvx2p0y3ya7oe7h4w1htxn8 foreign key (card_id) references kbcard (id);
alter table kblane add constraint FK8vd7f7xncptix3s7pomg84ywu foreign key (board_id) references kbboard (id);
alter table ktbrand_root_categories add constraint FK6i83j81rly6fwj9vwbraginoj foreign key (root_categories_id) references ktcategory (id);
alter table ktbrand_root_categories add constraint FK1b9br7dvdiyffh1n77ovleg99 foreign key (brands_id) references ktbrand (id);
alter table ktcategory add constraint FKiitp691nandbe28n36kw3lgi2 foreign key (master_index_id) references ktmaster_index (id);
alter table ktcategory add constraint FKmlr3xodmxxndafswww1p880b2 foreign key (root_category_id) references ktcategory (id);
alter table ktmodel add constraint FKsnmsv4pjxcfggmfnc8bpgttv9 foreign key (brand_id) references ktbrand (id);
alter table ktmodel add constraint FK68xsgfaujwndvwiht0cdiiqrw foreign key (root_category_id) references ktcategory (id);
